global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "agents"
    static_configs:
      - targets:
          - "oracle1:9464"
          - "blobd:9464"
          - "commit-reveal:9464"
          - "threshold:9464"
          - "seed:9464"
          - "iv:9464"
          - "settlement:9464"
          - "monitoring:9464"
          - "wsbridge:9464"
          - "deploy:9464"
  - job_name: "redis"
    static_configs:
      - targets: ["redis:9121"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - /etc/prometheus/alert.rules.yml 