global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node_bots"
    static_configs:
      - targets: ["exporter:9464"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - /etc/prometheus/alert.rules.yml 