version: "3.9"
services:
  oracle1:
    build: ../
    command: pnpm ts-node daemon/oracleBot.ts
    env_file: ../.env
    restart: always

  blobd:
    build: ../
    command: pnpm ts-node daemon/blobDaemon.ts
    env_file: ../.env
    restart: always

  commit-reveal:
    build: ../
    command: pnpm ts-node bots/commitRevealBot.ts
    env_file: ../.env
    restart: always

  threshold:
    build: ../
    command: pnpm ts-node bots/thresholdBot.ts
    env_file: ../.env
    restart: always

  seed:
    build: ../
    command: pnpm ts-node bots/seedBot.ts
    env_file: ../.env
    restart: always

  iv:
    build: ../
    command: pnpm ts-node bots/ivBot.ts
    env_file: ../.env
    restart: always

  wsbridge:
    build: ../
    command: pnpm ts-node daemon/wsBridge.ts
    env_file: ../.env
    ports: ["${WS_PORT:-6380}:${WS_PORT:-6380}"]
    restart: always

  settlement:
    build: ../
    command: pnpm ts-node bots/settleBot.ts
    env_file: ../.env
    restart: always

  monitoring:
    build: ../
    command: pnpm ts-node daemon/monitoringAgent.ts
    env_file: ../.env
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus:/etc/prometheus/"
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
