version: "3.9"
services:
  oracle1:
    build: ../
    command: pnpm ts-node daemon/oracleBot.ts
    env_file: ../.env
    restart: always

  blobd:
    build: ../
    command: pnpm ts-node daemon/blobDaemon.ts
    env_file: ../.env
    restart: always

  commit-reveal:
    build: ../
    command: pnpm ts-node bots/commitRevealBot.ts
    env_file: ../.env
    restart: always

  threshold:
    build: ../
    command: pnpm ts-node bots/thresholdBot.ts
    env_file: ../.env
    restart: always

  seed:
    build: ../
    command: pnpm ts-node bots/seedBot.ts
    env_file: ../.env
    restart: always

  iv:
    build: ../
    command: pnpm ts-node bots/ivBot.ts
    env_file: ../.env
    restart: always

  wsbridge:
    build: ../
    command: pnpm ts-node daemon/wsBridge.ts
    env_file: ../.env
    ports: ["${WS_PORT:-6380}:${WS_PORT:-6380}"]
    restart: always
